language: java
scala:
  - 2.11.7

os:
    - linux

before_install:
  - pushd .
  - cd
  - wget http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz
  - tar xzf scala-2.11.7.tgz
  - export SCALA_HOME=`pwd`/scala-2.11.7
  - export PATH=$SCALA_HOME/bin:$PATH
  - popd
  - env
  - scalac -version
  - which scalac
